name: car_rental_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.18
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.2
  file_picker: ^4.6.1
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  font_awesome_flutter: ">=4.7.0"
  get: ^4.6.5
  google_fonts: ^3.0.0
  grouped_buttons: any
  image_picker: ^0.8.5+3
  intl: ^0.17.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "assets/images/1024.png"
