name: car_rental_ui
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
color: '#ffffff'
image: assets/images/splash.png
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  community_material_icon: ^5.4.55
  cupertino_icons: ^1.0.2
  firebase_core: 1.17.1
  font_awesome_flutter: '>=4.7.0'
  google_fonts: ^3.0.0
  grouped_buttons: any
  firebase_auth: 3.3.19
  flutter: 
    sdk: flutter
  get: ^4.6.5

dev_dependencies: 
  flutter_native_splash: ^2.2.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
    - assets/logos/
  uses-material-design: true

flutter_native_splash: null
